"""Explicit schema for the loans table (SQLAlchemy Core, not ORM).

The table is the contract: column names, types, and NOT NULL. Pandas
to_sql would infer a sloppy schema; production code should not rely on that.
"""

from __future__ import annotations

from sqlalchemy import Column, Integer, MetaData, Table, Text

from src.data.database import TABLE_NAME

metadata = MetaData()

loans = Table(
    TABLE_NAME,
    metadata,
    Column("id", Integer, primary_key=True, autoincrement=True),
    Column("checking_status", Text, nullable=False),
    Column("duration", Integer, nullable=False),
    Column("credit_history", Text, nullable=False),
    Column("purpose", Text, nullable=False),
    Column("credit_amount", Integer, nullable=False),
    Column("savings_status", Text, nullable=False),
    Column("employment", Text, nullable=False),
    Column("installment_commitment", Integer, nullable=False),
    Column("personal_status", Text, nullable=False),
    Column("other_parties", Text, nullable=False),
    Column("residence_since", Integer, nullable=False),
    Column("property_magnitude", Text, nullable=False),
    Column("age", Integer, nullable=False),
    Column("other_payment_plans", Text, nullable=False),
    Column("housing", Text, nullable=False),
    Column("existing_credits", Integer, nullable=False),
    Column("job", Text, nullable=False),
    Column("num_dependents", Integer, nullable=False),
    Column("own_telephone", Text, nullable=False),
    Column("foreign_worker", Text, nullable=False),
    Column("credit_class", Text, nullable=False),
)

# Columns the CSV must supply after rename (id is generated by SQLite).
INGEST_COLUMNS = [column.name for column in loans.columns if column.name != "id"]
CREDIT_CLASSES = frozenset({"good", "bad"})
